#ifdef ARDUINO_AVR_YUN
  #define BOARD_MAP "AVR_YUN"
#endif

#ifdef ARDUINO_AVR_UNO
  #define BOARD_MAP "AVR_UNO"
#endif

#ifdef ARDUINO_AVR_DUEMILANOVE
  #define BOARD_MAP "AVR_DUEMILANOVE"
#endif

#ifdef ARDUINO_AVR_NANO
  #define BOARD_MAP "AVR_NANO"
#endif

#ifdef ARDUINO_AVR_MEGA2560
  #define BOARD_MAP "AVR_MEGA2560"
#endif

#ifdef ARDUINO_AVR_MEGA
  #define BOARD_MAP "AVR_MEGA"
#endif

#ifdef ARDUINO_AVR_ADK
  #define BOARD_MAP "AVR_ADK"
#endif

#ifdef ARDUINO_AVR_LEONARDO
  #define BOARD_MAP "AVR_LEONARDO"
#endif

#ifdef ARDUINO_AVR_LEONARDO_ETH
  #define BOARD_MAP "AVR_LEONARDO_ETH"
#endif

#ifdef ARDUINO_AVR_MICRO
  #define BOARD_MAP "AVR_MICRO"
#endif

#ifdef ARDUINO_AVR_ESPLORA
  #define BOARD_MAP "AVR_ESPLORA"
#endif

#ifdef ARDUINO_AVR_MINI
  #define BOARD_MAP "AVR_MINI"
#endif

#ifdef ARDUINO_AVR_ETHERNET
  #define BOARD_MAP "AVR_ETHERNET"
#endif

#ifdef ARDUINO_AVR_FIO
  #define BOARD_MAP "AVR_FIO"
#endif

#ifdef ARDUINO_AVR_BT
  #define BOARD_MAP "AVR_BT"
#endif

#ifdef ARDUINO_AVR_LILYPAD_USB
  #define BOARD_MAP "AVR_LILYPAD_USB"
#endif

#ifdef ARDUINO_AVR_LILYPAD
  #define BOARD_MAP "AVR_LILYPAD"
#endif

#ifdef ARDUINO_AVR_PRO
  #define BOARD_MAP "AVR_PRO"
#endif

#ifdef ARDUINO_AVR_NG
  #define BOARD_MAP "AVR_NG"
#endif

#ifdef ARDUINO_AVR_ROBOT_CONTROL
  #define BOARD_MAP "AVR_ROBOT_CONTROL"
#endif

#ifdef ARDUINO_AVR_ROBOT_MOTOR
  #define BOARD_MAP "AVR_ROBOT_MOTOR"
#endif

#ifdef ARDUINO_AVR_GEMMA
  #define BOARD_MAP "AVR_GEMMA"
#endif

#ifdef ARDUINO_AVR_CIRCUITPLAY
  #define BOARD_MAP "AVR_CIRCUITPLAY"
#endif

#ifdef ARDUINO_AVR_YUNMINI
  #define BOARD_MAP "AVR_YUNMINI"
#endif

#ifdef ARDUINO_AVR_INDUSTRIAL101
  #define BOARD_MAP "AVR_INDUSTRIAL101"
#endif

#ifdef ARDUINO_AVR_LININO_ONE
  #define BOARD_MAP "AVR_LININO_ONE"
#endif

#ifdef ARDUINO_AVR_UNO_WIFI_DEV_ED
  #define BOARD_MAP "AVR_UNO_WIFI_DEV_ED"
#endif

#ifdef ARDUINO_ESP32S3_DEV
  #define BOARD_MAP "ESP32S3_DEV"
#endif

#ifdef ARDUINO_ESP32C3_DEV
  #define BOARD_MAP "ESP32C3_DEV"
#endif

#ifdef ARDUINO_ESP32S2_DEV
  #define BOARD_MAP "ESP32S2_DEV"
#endif

#ifdef ARDUINO_ESP32_DEV
  #define BOARD_MAP "ESP32_DEV"
#endif

#ifdef ARDUINO_ESP32_WROOM_DA
  #define BOARD_MAP "ESP32_WROOM_DA"
#endif

#ifdef ARDUINO_ESP32_PICO
  #define BOARD_MAP "ESP32_PICO"
#endif

#ifdef ARDUINO_ESP32_S3_BOX
  #define BOARD_MAP "ESP32_S3_BOX"
#endif

#ifdef ARDUINO_ESP32_S3_USB_OTG
  #define BOARD_MAP "ESP32_S3_USB_OTG"
#endif

#ifdef ARDUINO_ESP32S3_CAM_LCD
  #define BOARD_MAP "ESP32S3_CAM_LCD"
#endif

#ifdef ARDUINO_ESP32S2_USB
  #define BOARD_MAP "ESP32S2_USB"
#endif

#ifdef ARDUINO_ESP32_WROVER_KIT
  #define BOARD_MAP "ESP32_WROVER_KIT"
#endif

#ifdef ARDUINO_TINYPICO
  #define BOARD_MAP "TINYPICO"
#endif

#ifdef ARDUINO_FEATHERS2
  #define BOARD_MAP "FEATHERS2"
#endif

#ifdef ARDUINO_FEATHERS2NEO
  #define BOARD_MAP "FEATHERS2NEO"
#endif

#ifdef ARDUINO_TINYS2
  #define BOARD_MAP "TINYS2"
#endif

#ifdef ARDUINO_RMP
  #define BOARD_MAP "RMP"
#endif

#ifdef ARDUINO_TINYS3
  #define BOARD_MAP "TINYS3"
#endif

#ifdef ARDUINO_PROS3
  #define BOARD_MAP "PROS3"
#endif

#ifdef ARDUINO_FEATHERS3
  #define BOARD_MAP "FEATHERS3"
#endif

#ifdef ARDUINO_LILYGO_T_DISPLAY_S3
  #define BOARD_MAP "LILYGO_T_DISPLAY_S3"
#endif

#ifdef ARDUINO_MICROS2
  #define BOARD_MAP "MICROS2"
#endif

#ifdef ARDUINO_TTGO_LoRa32_V1
  #define BOARD_MAP "TTGO_LoRa32_V1"
#endif

#ifdef ARDUINO_TTGO_LoRa32_V2
  #define BOARD_MAP "TTGO_LoRa32_V2"
#endif

#ifdef ARDUINO_TTGO_LoRa32_v21new
  #define BOARD_MAP "TTGO_LoRa32_v21new"
#endif

#ifdef ARDUINO_TTGO_T1
  #define BOARD_MAP "TTGO_T1"
#endif

#ifdef ARDUINO_TTGO_T7_V13_Mini32
  #define BOARD_MAP "TTGO_T7_V13_Mini32"
#endif

#ifdef ARDUINO_TTGO_T7_V14_Mini32
  #define BOARD_MAP "TTGO_T7_V14_Mini32"
#endif

#ifdef ARDUINO_TTGO-T-OI-PLUS_DEV
  #define BOARD_MAP "TTGO-T-OI-PLUS_DEV"
#endif

#ifdef ARDUINO_ESP32_THING
  #define BOARD_MAP "ESP32_THING"
#endif

#ifdef ARDUINO_ESP32_THING_PLUS
  #define BOARD_MAP "ESP32_THING_PLUS"
#endif

#ifdef ARDUINO_ESP32_THING_PLUS_C
  #define BOARD_MAP "ESP32_THING_PLUS_C"
#endif

#ifdef ARDUINO_ESP32S2_THING_PLUS
  #define BOARD_MAP "ESP32S2_THING_PLUS"
#endif

#ifdef ARDUINO_ESP32_MICROMOD
  #define BOARD_MAP "ESP32_MICROMOD"
#endif

#ifdef ARDUINO_ESP32_IOT_REDBOARD
  #define BOARD_MAP "ESP32_IOT_REDBOARD"
#endif

#ifdef ARDUINO_UBLOX_NINA_W10
  #define BOARD_MAP "UBLOX_NINA_W10"
#endif

#ifdef ARDUINO_UBLOX_NORA_W10
  #define BOARD_MAP "UBLOX_NORA_W10"
#endif

#ifdef ARDUINO_WIDORA_AIR
  #define BOARD_MAP "WIDORA_AIR"
#endif

#ifdef ARDUINO_ESP320
  #define BOARD_MAP "ESP320"
#endif

#ifdef ARDUINO_NANO32
  #define BOARD_MAP "NANO32"
#endif

#ifdef ARDUINO_LOLIN_D32
  #define BOARD_MAP "LOLIN_D32"
#endif

#ifdef ARDUINO_LOLIN_D32_PRO
  #define BOARD_MAP "LOLIN_D32_PRO"
#endif

#ifdef ARDUINO_LOLIN_C3_MINI
  #define BOARD_MAP "LOLIN_C3_MINI"
#endif

#ifdef ARDUINO_LOLIN_S2_MINI
  #define BOARD_MAP "LOLIN_S2_MINI"
#endif

#ifdef ARDUINO_LOLIN_S2_PICO
  #define BOARD_MAP "LOLIN_S2_PICO"
#endif

#ifdef ARDUINO_LOLIN_S3
  #define BOARD_MAP "LOLIN_S3"
#endif

#ifdef ARDUINO_LOLIN32
  #define BOARD_MAP "LOLIN32"
#endif

#ifdef ARDUINO_LOLIN32_LITE
  #define BOARD_MAP "LOLIN32_LITE"
#endif

#ifdef ARDUINO_Pocket32
  #define BOARD_MAP "Pocket32"
#endif

#ifdef ARDUINO_ESPea32
  #define BOARD_MAP "ESPea32"
#endif

#ifdef ARDUINO_QUANTUM
  #define BOARD_MAP "QUANTUM"
#endif

#ifdef ARDUINO_Node32s
  #define BOARD_MAP "Node32s"
#endif

#ifdef ARDUINO_HORNBILL_ESP32_DEV
  #define BOARD_MAP "HORNBILL_ESP32_DEV"
#endif

#ifdef ARDUINO_HORNBILL_ESP32_MINIMA
  #define BOARD_MAP "HORNBILL_ESP32_MINIMA"
#endif

#ifdef ARDUINO_DFROBOT_BEETLE_ESP32_C3
  #define BOARD_MAP "DFROBOT_BEETLE_ESP32_C3"
#endif

#ifdef ARDUINO_DFROBOT_FIREBEETLE_2_ESP32E
  #define BOARD_MAP "DFROBOT_FIREBEETLE_2_ESP32E"
#endif

#ifdef ARDUINO_DFROBOT_FIREBEETLE_2_ESP32S3
  #define BOARD_MAP "DFROBOT_FIREBEETLE_2_ESP32S3"
#endif

#ifdef ARDUINO_INTOROBOT_ESP32_DEV
  #define BOARD_MAP "INTOROBOT_ESP32_DEV"
#endif

#ifdef ARDUINO_ONEHORSE_ESP32_DEV
  #define BOARD_MAP "ONEHORSE_ESP32_DEV"
#endif

#ifdef ARDUINO_FEATHER_ESP32
  #define BOARD_MAP "FEATHER_ESP32"
#endif

#ifdef ARDUINO_METRO_ESP32S2
  #define BOARD_MAP "METRO_ESP32S2"
#endif

#ifdef ARDUINO_MAGTAG29_ESP32S2
  #define BOARD_MAP "MAGTAG29_ESP32S2"
#endif

#ifdef ARDUINO_FUNHOUSE_ESP32S2
  #define BOARD_MAP "FUNHOUSE_ESP32S2"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S2
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S2"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S2_TFT
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S2_TFT"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S2_REVTFT
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S2_REVTFT"
#endif

#ifdef ARDUINO_ADAFRUIT_QTPY_ESP32S2
  #define BOARD_MAP "ADAFRUIT_QTPY_ESP32S2"
#endif

#ifdef ARDUINO_ADAFRUIT_QTPY_ESP32C3
  #define BOARD_MAP "ADAFRUIT_QTPY_ESP32C3"
#endif

#ifdef ARDUINO_ADAFRUIT_QTPY_ESP32_PICO
  #define BOARD_MAP "ADAFRUIT_QTPY_ESP32_PICO"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32_V2
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32_V2"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S3
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S3"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S3_NOPSRAM
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S3_NOPSRAM"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S3_TFT
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S3_TFT"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_ESP32S3_REVTFT
  #define BOARD_MAP "ADAFRUIT_FEATHER_ESP32S3_REVTFT"
#endif

#ifdef ARDUINO_ADAFRUIT_QTPY_ESP32S3_NOPSRAM
  #define BOARD_MAP "ADAFRUIT_QTPY_ESP32S3_NOPSRAM"
#endif

#ifdef ARDUINO_ADAFRUIT_ITSYBITSY_ESP32
  #define BOARD_MAP "ADAFRUIT_ITSYBITSY_ESP32"
#endif

#ifdef ARDUINO_NodeMCU_32S
  #define BOARD_MAP "NodeMCU_32S"
#endif

#ifdef ARDUINO_MH_ET_LIVE_ESP32DEVKIT
  #define BOARD_MAP "MH_ET_LIVE_ESP32DEVKIT"
#endif

#ifdef ARDUINO_MH_ET_LIVE_ESP32MINIKIT
  #define BOARD_MAP "MH_ET_LIVE_ESP32MINIKIT"
#endif

#ifdef ARDUINO_esp32vn_iot_uno
  #define BOARD_MAP "esp32vn_iot_uno"
#endif

#ifdef ARDUINO_ESP32_EVB
  #define BOARD_MAP "ESP32_EVB"
#endif

#ifdef ARDUINO_ESP32_GATEWAY
  #define BOARD_MAP "ESP32_GATEWAY"
#endif

#ifdef ARDUINO_ESP32_GATEWAY_C
  #define BOARD_MAP "ESP32_GATEWAY_C"
#endif

#ifdef ARDUINO_ESP32_GATEWAY_E
  #define BOARD_MAP "ESP32_GATEWAY_E"
#endif

#ifdef ARDUINO_ESP32_GATEWAY_F
  #define BOARD_MAP "ESP32_GATEWAY_F"
#endif

#ifdef ARDUINO_ESP32_POE
  #define BOARD_MAP "ESP32_POE"
#endif

#ifdef ARDUINO_ESP32_POE_ISO
  #define BOARD_MAP "ESP32_POE_ISO"
#endif

#ifdef ARDUINO_ESP32_DEVKIT_LIPO
  #define BOARD_MAP "ESP32_DEVKIT_LIPO"
#endif

#ifdef ARDUINO_ESPino32
  #define BOARD_MAP "ESPino32"
#endif

#ifdef ARDUINO_M5Stack_Core_ESP32
  #define BOARD_MAP "M5Stack_Core_ESP32"
#endif

#ifdef ARDUINO_M5STACK_FIRE
  #define BOARD_MAP "M5STACK_FIRE"
#endif

#ifdef ARDUINO_M5Stack_Station
  #define BOARD_MAP "M5Stack_Station"
#endif

#ifdef ARDUINO_M5Stick_C
  #define BOARD_MAP "M5Stick_C"
#endif

#ifdef ARDUINO_M5Stack_ATOM
  #define BOARD_MAP "M5Stack_ATOM"
#endif

#ifdef ARDUINO_M5Stack_ATOMS3
  #define BOARD_MAP "M5Stack_ATOMS3"
#endif

#ifdef ARDUINO_M5STACK_Core2
  #define BOARD_MAP "M5STACK_Core2"
#endif

#ifdef ARDUINO_M5Stack-Timer-CAM
  #define BOARD_MAP "M5Stack-Timer-CAM"
#endif

#ifdef ARDUINO_M5Stack_CoreInk
  #define BOARD_MAP "M5Stack_CoreInk"
#endif

#ifdef ARDUINO_ODROID_ESP32
  #define BOARD_MAP "ODROID_ESP32"
#endif

#ifdef ARDUINO_heltec_wifi_kit_32
  #define BOARD_MAP "heltec_wifi_kit_32"
#endif

#ifdef ARDUINO_heltec_wifi_kit_32_V3
  #define BOARD_MAP "heltec_wifi_kit_32_V3"
#endif

#ifdef ARDUINO_heltec_wifi_lora_32
  #define BOARD_MAP "heltec_wifi_lora_32"
#endif

#ifdef ARDUINO_heltec_wifi_lora_32_V2
  #define BOARD_MAP "heltec_wifi_lora_32_V2"
#endif

#ifdef ARDUINO_heltec_wifi_32_lora_V3
  #define BOARD_MAP "heltec_wifi_32_lora_V3"
#endif

#ifdef ARDUINO_heltec_wireless_stick
  #define BOARD_MAP "heltec_wireless_stick"
#endif

#ifdef ARDUINO_heltec_wireless_stick_LITE
  #define BOARD_MAP "heltec_wireless_stick_LITE"
#endif

#ifdef ARDUINO_ESPECTRO32
  #define BOARD_MAP "ESPECTRO32"
#endif

#ifdef ARDUINO_CoreESP32
  #define BOARD_MAP "CoreESP32"
#endif

#ifdef ARDUINO_ALKS
  #define BOARD_MAP "ALKS"
#endif

#ifdef ARDUINO_WIPY3
  #define BOARD_MAP "WIPY3"
#endif

#ifdef ARDUINO_WT32_ETH01
  #define BOARD_MAP "WT32_ETH01"
#endif

#ifdef ARDUINO_BPI_BIT
  #define BOARD_MAP "BPI_BIT"
#endif

#ifdef ARDUINO_BPI_LEAF_S3
  #define BOARD_MAP "BPI_LEAF_S3"
#endif

#ifdef ARDUINO_WESP32
  #define BOARD_MAP "WESP32"
#endif

#ifdef ARDUINO_TBeam
  #define BOARD_MAP "TBeam"
#endif

#ifdef ARDUINO_TBEAM_USE_RADIO_SX1262
  #define BOARD_MAP "TBEAM_USE_RADIO_SX1262"
#endif

#ifdef ARDUINO_TBEAM_USE_RADIO_SX1276
  #define BOARD_MAP "TBEAM_USE_RADIO_SX1276"
#endif

#ifdef ARDUINO_TBEAM_USE_RADIO_SX1278
  #define BOARD_MAP "TBEAM_USE_RADIO_SX1278"
#endif

#ifdef ARDUINO_TBEAM_USE_RADIO_SX1280
  #define BOARD_MAP "TBEAM_USE_RADIO_SX1280"
#endif

#ifdef ARDUINO_TBEAM_USE_RADIO_SX1268
  #define BOARD_MAP "TBEAM_USE_RADIO_SX1268"
#endif

#ifdef ARDUINO_D_Duino_32
  #define BOARD_MAP "D_Duino_32"
#endif

#ifdef ARDUINO_LoPy
  #define BOARD_MAP "LoPy"
#endif

#ifdef ARDUINO_LoPy4
  #define BOARD_MAP "LoPy4"
#endif

#ifdef ARDUINO_OROCA_EDUBOT
  #define BOARD_MAP "OROCA_EDUBOT"
#endif

#ifdef ARDUINO_fm_devkit
  #define BOARD_MAP "fm_devkit"
#endif

#ifdef ARDUINO_FROG_ESP32
  #define BOARD_MAP "FROG_ESP32"
#endif

#ifdef ARDUINO_TWatch
  #define BOARD_MAP "TWatch"
#endif

#ifdef ARDUINO_TWATCH_BASE
  #define BOARD_MAP "TWATCH_BASE"
#endif

#ifdef ARDUINO_TWATCH_2020_V1
  #define BOARD_MAP "TWATCH_2020_V1"
#endif

#ifdef ARDUINO_TWATCH_2020_V2
  #define BOARD_MAP "TWATCH_2020_V2"
#endif

#ifdef ARDUINO_TWATCH_2020_V3
  #define BOARD_MAP "TWATCH_2020_V3"
#endif

#ifdef ARDUINO_D1_MINI32
  #define BOARD_MAP "D1_MINI32"
#endif

#ifdef ARDUINO_D1_UNO32
  #define BOARD_MAP "D1_UNO32"
#endif

#ifdef ARDUINO_PYCOM_GPY
  #define BOARD_MAP "PYCOM_GPY"
#endif

#ifdef ARDUINO_HONEYLEMON
  #define BOARD_MAP "HONEYLEMON"
#endif

#ifdef ARDUINO_MGBOT_IOTIK32A
  #define BOARD_MAP "MGBOT_IOTIK32A"
#endif

#ifdef ARDUINO_MGBOT_IOTIK32B
  #define BOARD_MAP "MGBOT_IOTIK32B"
#endif

#ifdef ARDUINO_Piranha
  #define BOARD_MAP "Piranha"
#endif

#ifdef ARDUINO_Metro
  #define BOARD_MAP "Metro"
#endif

#ifdef ARDUINO_sensesiot_weizen
  #define BOARD_MAP "sensesiot_weizen"
#endif

#ifdef ARDUINO_openkb
  #define BOARD_MAP "openkb"
#endif

#ifdef ARDUINO_Wifiduino32
  #define BOARD_MAP "Wifiduino32"
#endif

#ifdef ARDUINO_WiFiduinoV2
  #define BOARD_MAP "WiFiduinoV2"
#endif

#ifdef ARDUINO_WiFiduino32S3
  #define BOARD_MAP "WiFiduino32S3"
#endif

#ifdef ARDUINO_IMBRIOS_LOGSENS_V1P1
  #define BOARD_MAP "IMBRIOS_LOGSENS_V1P1"
#endif

#ifdef ARDUINO_HEALTHYPI_4
  #define BOARD_MAP "HEALTHYPI_4"
#endif

#ifdef ARDUINO_ET-Board
  #define BOARD_MAP "ET-Board"
#endif

#ifdef ARDUINO_DENKY
  #define BOARD_MAP "DENKY"
#endif

#ifdef ARDUINO_DENKY_PICOV3
  #define BOARD_MAP "DENKY_PICOV3"
#endif

#ifdef ARDUINO_DENKY_WROOM32
  #define BOARD_MAP "DENKY_WROOM32"
#endif

#ifdef ARDUINO_uPesy_WROVER
  #define BOARD_MAP "uPesy_WROVER"
#endif

#ifdef ARDUINO_uPesy_WROOM
  #define BOARD_MAP "uPesy_WROOM"
#endif

#ifdef ARDUINO_DYDK
  #define BOARD_MAP "DYDK"
#endif

#ifdef ARDUINO_DYDK1A
  #define BOARD_MAP "DYDK1A"
#endif

#ifdef ARDUINO_DYDK1Av2
  #define BOARD_MAP "DYDK1Av2"
#endif

#ifdef ARDUINO_DYM
  #define BOARD_MAP "DYM"
#endif

#ifdef ARDUINO_DYMv2
  #define BOARD_MAP "DYMv2"
#endif

#ifdef ARDUINO_DYG
  #define BOARD_MAP "DYG"
#endif

#ifdef ARDUINO_Trueverit_ESP32_Universal_IoT_Driver
  #define BOARD_MAP "Trueverit_ESP32_Universal_IoT_Driver"
#endif

#ifdef ARDUINO_Trueverit_ESP32_Universal_IoT_Driver_MK_II
  #define BOARD_MAP "Trueverit_ESP32_Universal_IoT_Driver_MK_II"
#endif

#ifdef ARDUINO_atmegazero_esp32s2
  #define BOARD_MAP "atmegazero_esp32s2"
#endif

#ifdef ARDUINO_FRANZININHO_WIFI
  #define BOARD_MAP "FRANZININHO_WIFI"
#endif

#ifdef ARDUINO_FRANZININHO_WIFI_MSC
  #define BOARD_MAP "FRANZININHO_WIFI_MSC"
#endif

#ifdef ARDUINO_TAMC_TERMOD_S3
  #define BOARD_MAP "TAMC_TERMOD_S3"
#endif

#ifdef ARDUINO_DPU_ESP32
  #define BOARD_MAP "DPU_ESP32"
#endif

#ifdef ARDUINO_SONOFF_DUALR3
  #define BOARD_MAP "SONOFF_DUALR3"
#endif

#ifdef ARDUINO_Lion:Bit_Dev_Board
  #define BOARD_MAP "Lion_Bit_Dev_Board"
#endif

#ifdef ARDUINO_WATCHY
  #define BOARD_MAP "WATCHY"
#endif

#ifdef ARDUINO_WATCHY_V10
  #define BOARD_MAP "WATCHY_V10"
#endif

#ifdef ARDUINO_WATCHY_V15
  #define BOARD_MAP "WATCHY_V15"
#endif

#ifdef ARDUINO_WATCHY_V20
  #define BOARD_MAP "WATCHY_V20"
#endif

#ifdef ARDUINO_AirM2M_CORE_ESP32C3
  #define BOARD_MAP "AirM2M_CORE_ESP32C3"
#endif

#ifdef ARDUINO_XIAO_ESP32C3
  #define BOARD_MAP "XIAO_ESP32C3"
#endif

#ifdef ARDUINO_connaxio_espoir
  #define BOARD_MAP "connaxio_espoir"
#endif

#ifdef ARDUINO_DEPARTMENT_OF_ALCHEMY_MINIMAIN_ESP32S2
  #define BOARD_MAP "DEPARTMENT_OF_ALCHEMY_MINIMAIN_ESP32S2"
#endif

#ifdef ARDUINO_BeeMotionS3
  #define BOARD_MAP "BeeMotionS3"
#endif

#ifdef ARDUINO_Bee_Motion
  #define BOARD_MAP "Bee_Motion"
#endif

#ifdef ARDUINO_Bee_Motion_Mini
  #define BOARD_MAP "Bee_Motion_Mini"
#endif

#ifdef ARDUINO_Bee_S3
  #define BOARD_MAP "Bee_S3"
#endif

#ifdef ARDUINO_unphone8
  #define BOARD_MAP "unphone8"
#endif

#ifdef ARDUINO_unphone9
  #define BOARD_MAP "unphone9"
#endif

#ifdef ARDUINO_CYTRON_MAKER_FEATHER_AIOT_S3
  #define BOARD_MAP "CYTRON_MAKER_FEATHER_AIOT_S3"
#endif

#ifdef ARDUINO_REDPILL_ESP32S3
  #define BOARD_MAP "REDPILL_ESP32S3"
#endif

#ifdef ARDUINO_ESP32C3_M1_I_KIT
  #define BOARD_MAP "ESP32C3_M1_I_KIT"
#endif

#ifdef ARDUINO_roboheart_hercules
  #define BOARD_MAP "roboheart_hercules"
#endif

#ifdef ARDUINO_VALTRACK_V4_VTS_ESP32_C3
  #define BOARD_MAP "VALTRACK_V4_VTS_ESP32_C3"
#endif

#ifdef ARDUINO_VALTRACK_V4_MFW_ESP32_C3
  #define BOARD_MAP "VALTRACK_V4_MFW_ESP32_C3"
#endif

#ifdef ARDUINO_Edgebox-ESP-100
  #define BOARD_MAP "Edgebox-ESP-100"
#endif

#ifdef ARDUINO_CRABIK_SLOT_ESP32_S3
  #define BOARD_MAP "CRABIK_SLOT_ESP32_S3"
#endif

#ifdef ARDUINO_ESP8266_GENERIC
  #define BOARD_MAP "ESP8266_GENERIC"
#endif

#ifdef ARDUINO_ESP8266_ESP01
  #define BOARD_MAP "ESP8266_ESP01"
#endif

#ifdef ARDUINO_GEN4_IOD
  #define BOARD_MAP "GEN4_IOD"
#endif

#ifdef ARDUINO_ESP8266_ADAFRUIT_HUZZAH
  #define BOARD_MAP "ESP8266_ADAFRUIT_HUZZAH"
#endif

#ifdef ARDUINO_AMPERKA_WIFI_SLOT
  #define BOARD_MAP "AMPERKA_WIFI_SLOT"
#endif

#ifdef ARDUINO_ESP8266_ARDUINO_PRIMO
  #define BOARD_MAP "ESP8266_ARDUINO_PRIMO"
#endif

#ifdef ARDUINO_ESP8266_ARDUINO_STAR_OTTO
  #define BOARD_MAP "ESP8266_ARDUINO_STAR_OTTO"
#endif

#ifdef ARDUINO_ESP8266_ARDUINO_UNOWIFI
  #define BOARD_MAP "ESP8266_ARDUINO_UNOWIFI"
#endif

#ifdef ARDUINO_ESP8266_OAK
  #define BOARD_MAP "ESP8266_OAK"
#endif

#ifdef ARDUINO_ESP8266_ESP13
  #define BOARD_MAP "ESP8266_ESP13"
#endif

#ifdef ARDUINO_ESP8266_ESPECTRO_CORE
  #define BOARD_MAP "ESP8266_ESPECTRO_CORE"
#endif

#ifdef ARDUINO_ESP8266_ESPINO_ESP12
  #define BOARD_MAP "ESP8266_ESPINO_ESP12"
#endif

#ifdef ARDUINO_ESP8266_ESPRESSO_LITE_V1
  #define BOARD_MAP "ESP8266_ESPRESSO_LITE_V1"
#endif

#ifdef ARDUINO_ESP8266_ESPRESSO_LITE_V2
  #define BOARD_MAP "ESP8266_ESPRESSO_LITE_V2"
#endif

#ifdef ARDUINO_ESP8266_SONOFF_SV
  #define BOARD_MAP "ESP8266_SONOFF_SV"
#endif

#ifdef ARDUINO_ESP8266_SONOFF_BASIC
  #define BOARD_MAP "ESP8266_SONOFF_BASIC"
#endif

#ifdef ARDUINO_ESP8266_SONOFF_S20
  #define BOARD_MAP "ESP8266_SONOFF_S20"
#endif

#ifdef ARDUINO_ESP8266_SONOFF_TH
  #define BOARD_MAP "ESP8266_SONOFF_TH"
#endif

#ifdef ARDUINO_ESP8266_INVENT_ONE
  #define BOARD_MAP "ESP8266_INVENT_ONE"
#endif

#ifdef ARDUINO_ESP8266_WEMOS_D1WROOM02
  #define BOARD_MAP "ESP8266_WEMOS_D1WROOM02"
#endif

#ifdef ARDUINO_ESP8266_WEMOS_D1MINI
  #define BOARD_MAP "ESP8266_WEMOS_D1MINI"
#endif

#ifdef ARDUINO_ESP8266_WEMOS_D1MINILITE
  #define BOARD_MAP "ESP8266_WEMOS_D1MINILITE"
#endif

#ifdef ARDUINO_ESP8266_WEMOS_D1MINIPRO
  #define BOARD_MAP "ESP8266_WEMOS_D1MINIPRO"
#endif

#ifdef ARDUINO_ESP8266_WEMOS_D1R1
  #define BOARD_MAP "ESP8266_WEMOS_D1R1"
#endif

#ifdef ARDUINO_ESP8266_AGRUMINO_LEMON_V4
  #define BOARD_MAP "ESP8266_AGRUMINO_LEMON_V4"
#endif

#ifdef ARDUINO_ESP8266_NODEMCU_ESP12
  #define BOARD_MAP "ESP8266_NODEMCU_ESP12"
#endif

#ifdef ARDUINO_ESP8266_NODEMCU_ESP12E
  #define BOARD_MAP "ESP8266_NODEMCU_ESP12E"
#endif

#ifdef ARDUINO_MOD_WIFI_ESP8266
  #define BOARD_MAP "MOD_WIFI_ESP8266"
#endif

#ifdef ARDUINO_ESP8266_PHOENIX_V1
  #define BOARD_MAP "ESP8266_PHOENIX_V1"
#endif

#ifdef ARDUINO_ESP8266_PHOENIX_V2
  #define BOARD_MAP "ESP8266_PHOENIX_V2"
#endif

#ifdef ARDUINO_ESP8266_SCHIRMILABS_EDUINO_WIFI
  #define BOARD_MAP "ESP8266_SCHIRMILABS_EDUINO_WIFI"
#endif

#ifdef ARDUINO_ESP8266_WIO_LINK
  #define BOARD_MAP "ESP8266_WIO_LINK"
#endif

#ifdef ARDUINO_ESP8266_THING
  #define BOARD_MAP "ESP8266_THING"
#endif

#ifdef ARDUINO_ESP8266_THING_DEV
  #define BOARD_MAP "ESP8266_THING_DEV"
#endif

#ifdef ARDUINO_ESP8266_ESP210
  #define BOARD_MAP "ESP8266_ESP210"
#endif

#ifdef ARDUINO_ESP8266_ESPINO_ESP13
  #define BOARD_MAP "ESP8266_ESPINO_ESP13"
#endif

#ifdef ARDUINO_wifi_kit_8
  #define BOARD_MAP "wifi_kit_8"
#endif

#ifdef ARDUINO_WIFIDUINO_ESP8266
  #define BOARD_MAP "WIFIDUINO_ESP8266"
#endif

#ifdef ARDUINO_WIFINFO
  #define BOARD_MAP "WIFINFO"
#endif

#ifdef ARDUINO_ESP8266_ESP07
  #define BOARD_MAP "ESP8266_ESP07"
#endif

#ifdef ARDUINO_ESP8266_ESP12
  #define BOARD_MAP "ESP8266_ESP12"
#endif

#ifdef ARDUINO_ESP8266_XINABOX_CW01
  #define BOARD_MAP "ESP8266_XINABOX_CW01"
#endif

#ifdef ARDUINO_AVR_UNO_WIFI_REV2
  #define BOARD_MAP "AVR_UNO_WIFI_REV2"
#endif

#ifdef ARDUINO_AVR_NANO_EVERY
  #define BOARD_MAP "AVR_NANO_EVERY"
#endif

#ifdef ARDUINO_RASPBERRY_PI_PICO
  #define BOARD_MAP "RASPBERRY_PI_PICO"
#endif

#ifdef ARDUINO_RASPBERRY_PI_PICO_W
  #define BOARD_MAP "RASPBERRY_PI_PICO_W"
#endif

#ifdef ARDUINO_0XCB_HELIOS
  #define BOARD_MAP "0XCB_HELIOS"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040_SCORPIO
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040_SCORPIO"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040_DVI
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040_DVI"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040_RFM
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040_RFM"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040_THINKINK
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040_THINKINK"
#endif

#ifdef ARDUINO_ADAFRUIT_FEATHER_RP2040_USB_HOST
  #define BOARD_MAP "ADAFRUIT_FEATHER_RP2040_USB_HOST"
#endif

#ifdef ARDUINO_ADAFRUIT_ITSYBITSY_RP2040
  #define BOARD_MAP "ADAFRUIT_ITSYBITSY_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_QTPY_RP2040
  #define BOARD_MAP "ADAFRUIT_QTPY_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_STEMMAFRIEND_RP2040
  #define BOARD_MAP "ADAFRUIT_STEMMAFRIEND_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_TRINKEYQT_RP2040
  #define BOARD_MAP "ADAFRUIT_TRINKEYQT_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_MACROPAD_RP2040
  #define BOARD_MAP "ADAFRUIT_MACROPAD_RP2040"
#endif

#ifdef ARDUINO_ADAFRUIT_KB2040_RP2040
  #define BOARD_MAP "ADAFRUIT_KB2040_RP2040"
#endif

#ifdef ARDUINO_NANO_RP2040_CONNECT
  #define BOARD_MAP "NANO_RP2040_CONNECT"
#endif

#ifdef ARDUINO_BRIDGETEK_IDM2040-7A
  #define BOARD_MAP "BRIDGETEK_IDM2040-7A"
#endif

#ifdef ARDUINO_CYTRON_MAKER_NANO_RP2040
  #define BOARD_MAP "CYTRON_MAKER_NANO_RP2040"
#endif

#ifdef ARDUINO_CYTRON_MAKER_PI_RP2040
  #define BOARD_MAP "CYTRON_MAKER_PI_RP2040"
#endif

#ifdef ARDUINO_DATANOISETV_PICOADK
  #define BOARD_MAP "DATANOISETV_PICOADK"
#endif

#ifdef ARDUINO_FLYBOARD2040_CORE
  #define BOARD_MAP "FLYBOARD2040_CORE"
#endif

#ifdef ARDUINO_DFROBOT_BEETLE_RP2040
  #define BOARD_MAP "DFROBOT_BEETLE_RP2040"
#endif

#ifdef ARDUINO_ELECTRONICCATS_HUNTERCAT_NFC
  #define BOARD_MAP "ELECTRONICCATS_HUNTERCAT_NFC"
#endif

#ifdef ARDUINO_EXTREMEELEXTRONICS_RC2040
  #define BOARD_MAP "EXTREMEELEXTRONICS_RC2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_LTE_RP2040
  #define BOARD_MAP "CHALLENGER_2040_LTE_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_LORA_RP2040
  #define BOARD_MAP "CHALLENGER_2040_LORA_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_SUBGHZ_RP2040
  #define BOARD_MAP "CHALLENGER_2040_SUBGHZ_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_WIFI_RP2040
  #define BOARD_MAP "CHALLENGER_2040_WIFI_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_WIFI_BLE_RP2040
  #define BOARD_MAP "CHALLENGER_2040_WIFI_BLE_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_NB_2040_WIFI_RP2040
  #define BOARD_MAP "CHALLENGER_NB_2040_WIFI_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_SDRTC_RP2040
  #define BOARD_MAP "CHALLENGER_2040_SDRTC_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_NFC_RP2040
  #define BOARD_MAP "CHALLENGER_2040_NFC_RP2040"
#endif

#ifdef ARDUINO_CHALLENGER_2040_UWB_RP2040
  #define BOARD_MAP "CHALLENGER_2040_UWB_RP2040"
#endif

#ifdef ARDUINO_ILABS_2040_RPICO32_RP2040
  #define BOARD_MAP "ILABS_2040_RPICO32_RP2040"
#endif

#ifdef ARDUINO_MELOPERO_COOKIE_RP2040
  #define BOARD_MAP "MELOPERO_COOKIE_RP2040"
#endif

#ifdef ARDUINO_MELOPERO_SHAKE_RP2040
  #define BOARD_MAP "MELOPERO_SHAKE_RP2040"
#endif

#ifdef ARDUINO_NEKOSYSTEMS_BL2040_MINI
  #define BOARD_MAP "NEKOSYSTEMS_BL2040_MINI"
#endif

#ifdef ARDUINO_NULLBITS_BIT_C_PRO
  #define BOARD_MAP "NULLBITS_BIT_C_PRO"
#endif

#ifdef ARDUINO_PIMORONI_PGA2040
  #define BOARD_MAP "PIMORONI_PGA2040"
#endif

#ifdef ARDUINO_SOLDERPARTY_RP2040_STAMP
  #define BOARD_MAP "SOLDERPARTY_RP2040_STAMP"
#endif

#ifdef ARDUINO_SPARKFUN_PROMICRO_RP2040
  #define BOARD_MAP "SPARKFUN_PROMICRO_RP2040"
#endif

#ifdef ARDUINO_SPARKFUN_THINGPLUS_RP2040
  #define BOARD_MAP "SPARKFUN_THINGPLUS_RP2040"
#endif

#ifdef ARDUINO_UPESY_RP2040_DEVKIT
  #define BOARD_MAP "UPESY_RP2040_DEVKIT"
#endif

#ifdef ARDUINO_SEEED_XIAO_RP2040
  #define BOARD_MAP "SEEED_XIAO_RP2040"
#endif

#ifdef ARDUINO_YD_RP2040
  #define BOARD_MAP "YD_RP2040"
#endif

#ifdef ARDUINO_VIYALAB_MIZU_RP2040
  #define BOARD_MAP "VIYALAB_MIZU_RP2040"
#endif

#ifdef ARDUINO_WAVESHARE_RP2040_ZERO
  #define BOARD_MAP "WAVESHARE_RP2040_ZERO"
#endif

#ifdef ARDUINO_WAVESHARE_RP2040_ONE
  #define BOARD_MAP "WAVESHARE_RP2040_ONE"
#endif

#ifdef ARDUINO_WAVESHARE_RP2040_PLUS
  #define BOARD_MAP "WAVESHARE_RP2040_PLUS"
#endif

#ifdef ARDUINO_WAVESHARE_RP2040_LCD_0_96
  #define BOARD_MAP "WAVESHARE_RP2040_LCD_0_96"
#endif

#ifdef ARDUINO_WAVESHARE_RP2040_LCD_1_28
  #define BOARD_MAP "WAVESHARE_RP2040_LCD_1_28"
#endif

#ifdef ARDUINO_WIZNET_5100S_EVB_PICO
  #define BOARD_MAP "WIZNET_5100S_EVB_PICO"
#endif

#ifdef ARDUINO_WIZNET_WIZFI360_EVB_PICO
  #define BOARD_MAP "WIZNET_WIZFI360_EVB_PICO"
#endif

#ifdef ARDUINO_WIZNET_5500_EVB_PICO
  #define BOARD_MAP "WIZNET_5500_EVB_PICO"
#endif

#ifdef ARDUINO_GENERIC_RP2040
  #define BOARD_MAP "GENERIC_RP2040"
#endif

#ifdef ARDUINO_SAM_DUE
  #define BOARD_MAP "SAM_DUE"
#endif

#ifdef ARDUINO_SAMD_ZERO
  #define BOARD_MAP "SAMD_ZERO"
#endif

#ifdef ARDUINO_SAMD_MKR1000
  #define BOARD_MAP "SAMD_MKR1000"
#endif

#ifdef ARDUINO_SAMD_MKRZERO
  #define BOARD_MAP "SAMD_MKRZERO"
#endif

#ifdef ARDUINO_SAMD_MKRWIFI1010
  #define BOARD_MAP "SAMD_MKRWIFI1010"
#endif

#ifdef ARDUINO_SAMD_NANO_33_IOT
  #define BOARD_MAP "SAMD_NANO_33_IOT"
#endif

#ifdef ARDUINO_SAMD_MKRFox1200
  #define BOARD_MAP "SAMD_MKRFox1200"
#endif

#ifdef ARDUINO_SAMD_MKRWAN1300
  #define BOARD_MAP "SAMD_MKRWAN1300"
#endif

#ifdef ARDUINO_SAMD_MKRWAN1310
  #define BOARD_MAP "SAMD_MKRWAN1310"
#endif

#ifdef ARDUINO_SAMD_MKRGSM1400
  #define BOARD_MAP "SAMD_MKRGSM1400"
#endif

#ifdef ARDUINO_SAMD_MKRNB1500
  #define BOARD_MAP "SAMD_MKRNB1500"
#endif

#ifdef ARDUINO_SAMD_MKRVIDOR4000
  #define BOARD_MAP "SAMD_MKRVIDOR4000"
#endif

#ifdef ARDUINO_SAMD_CIRCUITPLAYGROUND_EXPRESS
  #define BOARD_MAP "SAMD_CIRCUITPLAYGROUND_EXPRESS"
#endif

#ifdef ARDUINO_SAM_ZERO
  #define BOARD_MAP "SAM_ZERO"
#endif

#ifdef ARDUINO_SAMD_TIAN
  #define BOARD_MAP "SAMD_TIAN"
#endif

